// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabularyTrainer.Data.Data;

#nullable disable

namespace VocabularyTrainer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("VocabularyTrainer.Data.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Croatian")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleSentence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("French")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("German")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flashcards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Croatian = "Kuća",
                            English = "House",
                            ExampleSentence = "Das Haus ist groß.",
                            French = "Maison",
                            German = "Haus"
                        },
                        new
                        {
                            Id = 2,
                            Croatian = "Drvo",
                            English = "Tree",
                            ExampleSentence = "Der Baum ist hoch.",
                            French = "Arbre",
                            German = "Baum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
